Added project files
ankitt26/First-Microverse-Project pull request #1
Opened 2023-03-21 21:20 UTC by ankitt26

In this branch i did -

- [ ]  Add index.html  file.
- [ ]  Add styles.css  file.
- [ ]  Add linters.yml file.
- [ ] Add readme.md file.

2023-03-21 21:43 UTC, Qoosim requested changes
#  *Status: Required Changes* :recycle:

Hi @ankitt26, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
-  No linter errors. :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 
-  Correct GitHub Flow. :heavy_check_mark: 

![](https://camo.githubusercontent.com/38ce8c8b213b08e2d9bb85a0b79702ad512f3910f803ec3d7917b4e0110c9044/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f7741366159414f336a4836526d55494259732f67697068792e676966)


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-21 21:43 UTC, Qoosim commented on README.md
> +> Describe your project in 1 or 2 sentences.
- [ ] Kindly remove this line. It is there to inform you what to do.

2023-03-21 21:43 UTC, Qoosim commented on README.md
> +> Describe the tech stack and include only the relevant sections that apply to your project.
- [ ] Same thing goes for this too

2023-03-21 21:43 UTC, Qoosim commented on README.md
> +> Describe between 1-3 key features of the application.
- [ ] Same thing here

2023-03-21 21:43 UTC, Qoosim commented on README.md
> +> Describe how a new developer could make use of your project.
- [ ] Same thing here

2023-03-21 21:43 UTC, Qoosim commented on README.md
> +> Mention all of the collaborators of this project.
- [ ] Same thing here

2023-03-21 21:43 UTC, Qoosim commented on README.md
> +> Describe 1 - 3 features you will add to the project.
- [ ] Same thing here.

2023-03-22 06:47 UTC, ankitt26 commented
Modified Readme.md file

2023-03-22 07:02 UTC, Shedrack-Sunday approved these changes
# STATUS: APPROVED ♻️♻️
Hi @ankitt26 

To highlight 👍🏽
✔️ All suggested changes made
✔️ No linter errors

Your project is complete! There is nothing else to say other than... it's time to merge it 🚀
Congratulations! 🎉

## Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better.


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

2023-03-22 07:54 UTC, merged